name: Publish branch image

on:
  push:
    branches:
      - main  # Собираем при пуше в main ветку

env:
  GHCR_REGISTRY_HOST: ghcr.io
  GHCR_REGISTRY_USERNAME: ${{ secrets.PACKAGES_USER }}
  GHCR_REGISTRY_PASSWORD: ${{ secrets.PACKAGES_TOKEN }}

jobs:
  create-latest-image:
    name: Create branch docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Create tag image
        run: |
          echo "GHCR_IMAGE_APP=${{ env.GHCR_REGISTRY_HOST }}/${GITHUB_REPOSITORY,,}-app:${GITHUB_REF##*/}" >> ${GITHUB_ENV}
          echo "GHCR_IMAGE_BACKEND=${{ env.GHCR_REGISTRY_HOST }}/${GITHUB_REPOSITORY,,}-backend:${GITHUB_REF##*/}" >> ${GITHUB_ENV}
          echo "GHCR_IMAGE_DATABASE=${{ env.GHCR_REGISTRY_HOST }}/${GITHUB_REPOSITORY,,}-database:${GITHUB_REF##*/}" >> ${GITHUB_ENV}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHCR_REGISTRY_HOST }}
          username: ${{ env.GHCR_REGISTRY_USERNAME }}
          password: ${{ env.GHCR_REGISTRY_PASSWORD }}

      -
        # ${login}/${repository-name}-app
        name: Build and push app
        uses: docker/build-push-action@v4
        with:
          context: ./containers/app
          platforms: linux/amd64
#          platforms: linux/amd64,linux/arm64
          push: true
          # ${login}/${repository-name}-app
          tags: |
            ${{ env.GHCR_IMAGE_APP }}

      -
        # ${login}/${repository-name}-app
        name: Build and push database
        uses: docker/build-push-action@v4
        with:
          context: ./containers/database
          platforms: linux/amd64
          #          platforms: linux/amd64,linux/arm64
          push: true
          # ${login}/${repository-name}-app
          tags: |
            ${{ env.GHCR_IMAGE_DATABASE }}


      -
        name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./containers/backend
          platforms: linux/amd64
#          platforms: linux/amd64,linux/arm64
          push: true
          # ${login}/${repository-name}-backend
          tags: |
            ${{ env.GHCR_IMAGE_BACKEND }}
            
